### ISSUE TITLE
May not play nicely with 11ty 2.0

### ISSUE THREAD

**Issue by jamesdoc** [patrickxchong/eleventy-plugin-svg-sprite#11]
With 2.0 on the horizon I had a quick poke with the canary build, and it doesn't seem to be playing nicely with together with svg-sprite 😢 

```
[11ty] File changed: .eleventy.js
[11ty] Eleventy watch error: (more in DEBUG output)
[11ty] 1. Error in your Eleventy config file '.eleventy.js'. You may need to run `npm install`. (via EleventyConfigError)
[11ty] 2. Cannot find module 'glob'
[11ty] Require stack:
[11ty] - /Users/itsame/Developer/Sites/thesite/node_modules/eleventy-plugin-svg-sprite/src/SVGSprite.js
```

```
npm ERR! code ERESOLVE
npm ERR! ERESOLVE could not resolve
npm ERR! 
npm ERR! While resolving: eleventy-plugin-svg-sprite@2.1.0
npm ERR! Found: @11ty/eleventy@2.0.0-canary.30
npm ERR! node_modules/@11ty/eleventy
npm ERR!   dev @11ty/eleventy@"^2.0.0-canary.30" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer @11ty/eleventy@">=0.5.4" from eleventy-plugin-svg-sprite@2.1.0
npm ERR! node_modules/eleventy-plugin-svg-sprite
npm ERR!   dev eleventy-plugin-svg-sprite@"^2.1.0" from the root project
npm ERR! 
npm ERR! Conflicting peer dependency: @11ty/eleventy@1.0.2
npm ERR! node_modules/@11ty/eleventy
npm ERR!   peer @11ty/eleventy@">=0.5.4" from eleventy-plugin-svg-sprite@2.1.0
npm ERR!   node_modules/eleventy-plugin-svg-sprite
npm ERR!     dev eleventy-plugin-svg-sprite@"^2.1.0" from the root project
```

**Comment by patrickxchong** [comment]
Hey James, thanks for raising the issue and helping out with the other issue (wasn't able to look at it, been going through some difficult times). 

The first seems to be a pretty basic dependency issue, I didn't explicitly specify `glob` in my dependency list, it must've been used previously in Eleventy V1 but they removed that dependency, I'll add that in.
https://www.npmjs.com/package/glob

The second likely has to do with the `-canary.30` text not fulfilling the `>=0.5.4` condition I have in the `package.json`. I'm pretty sure the behaviour described in `Prerelease Tags` in the 2nd link below covers the reason why the error is showing up for you.
https://docs.npmjs.com/cli/v9/configuring-npm/package-json#dependencies
https://github.com/npm/node-semver#prerelease-tags

Appreciate your concern on this!

**Comment by jamesdoc** [comment]
I think that you're absolutely right on both accounts.

If anyone else is keen to bump to `2.0 beta` then here is the commit that makes this a smooth path until that everything is out of beta: https://github.com/theglobechurch/globe-static/commit/10fd9b9ea98bf244eada800074de35e290ceba75

**Comment by shanerobinson** [comment]
After 2 hours of trying everything... And finally stripping all references to the SVG Sprite plugin in order to get 11ty 2.0.1 to build, I found this and HOPED it would work just by installing glob 10.2.6.... Nope. SVG Sprite is still the problem: 


[11ty] Problem writing Eleventy templates: (more in DEBUG output)
[11ty] The "original" argument must be of type function. Received an instance of Object (via TypeError)
[11ty] 
[11ty] Original error stack trace: TypeError [ERR_INVALID_ARG_TYPE]: The "original" argument must be of type function. Received an instance of Object
[11ty]     at Object.promisify (node:internal/util:329:3)
[11ty]     at SVGSprite.compile (/---my-path---/11ta-template/node_modules/eleventy-plugin-svg-sprite/src/SVGSprite.js:18:25)
[11ty]     at AsyncEventEmitter.<anonymous> (/---my-path---/11ta-template/node_modules/eleventy-plugin-svg-sprite/.eleventy.js:25:76)
[11ty]     at /---my-path---/11ta-template/node_modules/@11ty/eleventy/src/Util/AsyncEventEmitter.js:19:61
[11ty]     at Array.map (<anonymous>)
[11ty]     at AsyncEventEmitter.emit (/---my-path---/11ta-template/node_modules/@11ty/eleventy/src/Util/AsyncEventEmitter.js:19:34)
[11ty]     at Eleventy.executeBuild (/---my-path---/11ta-template/node_modules/@11ty/eleventy/src/Eleventy.js:1175:32)
[11ty]     at Eleventy.write (/---my-path---/11ta-template/node_modules/@11ty/eleventy/src/Eleventy.js:1109:17)
[11ty]     at /---my-path---/11ta-template/node_modules/@11ty/eleventy/cmd.js:116:20
[11ty] Wrote 0 files in 0.00 seconds (v2.0.1)
ERROR: "build:eleventy" exited with 1.

**Comment by patrickxchong** [comment]
@jamesdoc @shanerobinson I finally had the time to look into this a bit more. Have explicitly installed Glob v10 and updated the code to use the `glob` function that supports promises. Published `v2.4.2` with the fix. Apologies for all inconveniences caused. :pray:
